export const RoadClosureFeilds = [
    {
      id: '1',
      label: 'Road Closure Date',
      type: 'default',
      text: 'date',
      placeholder: 'Road Closure Date',
      name:'roadclouseR_STARTDATE',
    },
    {
      id: '2',
      label: 'Road Closure Start Time',
      type: 'default',
      text: 'time',
      placeholder: 'Road Closure Start Time',
      name:'roadclouseR_STARTTIME',
    },{
      id: '3',
      label: 'Road Closure End Date',
      type: 'default',
      text: 'date',
      placeholder: 'Road Closure End Date',
      name:'roadclouseR_ENDDATE',
    },
    ,{
      id: '4',
      label: 'Road Closure End Time',
      type: 'default',
      text: 'time',
      placeholder: 'Road Closure End Time',
      name:'roadclouseR_ENDTIME',
    },
    {
      id: '5',
      label: 'Location',
      type: 'default',
      // text: 'textarea',
      placeholder: 'Location',
      name:'location',
    },
    {
      id: '6',
      label: 'Name of the Road',
      type: 'default',
      // text: 'textarea',
      placeholder: 'Name of the Road',
      name:'roaD_NAME',
    },
    {
      id: '7',
      label: 'Road Closure Details',
      type: 'default',
      text: 'textarea',
      placeholder: 'Road Closure Details',
      name:'roadclouseR_DETAILS',
    },
    // {
    //   id: '3',
    //   label: 'Category',
    //   type: 'default',
    //   text: 'dropdown',
    //   placeholder: 'Category',
    // },
    // {
    //   id: '4',
    //   label: 'Crime Hotspot Details',
    //   type: 'default',
    //   text: 'tetarea',
    //   placeholder: 'Crime Hotspot Details',
    // },
    // {
    //   id: '8',
    //   label: 'Ward Number',
    //   type: 'numeric',
    //   text: 'numeric',
    //   placeholder: 'Ward Number',
    //   name:'WARD_NO',
    // },
    // {
    //   id: '9',
    //   label: 'Expire Date',
    //   type: 'default',
    //   text: 'date',
    //   placeholder: 'Expire Date',
    //   name:'expirY_DETAILS',
    // }
  ];
  