export const SingupFileds = [
  {
    id: '1',
    label: 'Title',
    name:'title',
    type: 'default',
    text:'dropdown',
    value:'',
    placeholder: 'Title',
  },
  {
    id: '2',
    label: 'First Name',
    name:'firstName',
    value:'',
    type: 'default',
    placeholder: 'First Name',
  },
  {
    id: '3',
    label: 'Last Name',
    name:'lastName',
    value:'',
    type: 'default',
    placeholder: 'Last Name',
  },  
  {
    id: '4',
    label: 'ID Number',
    name:'IDNumber',
    value:'',
    type: 'numeric',
    placeholder: 'ID Number',
  },
  {
    id: '5',
    label: 'Cell Number',
    name:'cellNumber',
    value:'',
    type: 'numeric',
    placeholder: 'Cell Number',
  },
  {
    id: '6',
    label: 'Email',
    name:'email',
    value:'',
    type: 'email-address',
    placeholder: 'Email',
  },
  {
    id: '7',
    label: 'Password',
    name:'password',
    value:'',
    type: 'default',
    placeholder: 'Password',
  },
  {
    id: '8',
    label: 'Confirm Password',
    name:'confirmPassword',
    value:'',
    type: 'default',
    placeholder: 'Confirm Password',
  },
  {
    id: '9',
    label: 'Address',
    name:'address',
    value:'',
    type: 'default',
    text:'tetarea',
    placeholder: 'Address',
  },
  
  {
    id: '10',
    label: 'Ward Number',
    name:'wardNo',
    value:'',
    type: 'numeric',
    placeholder: 'Ward Number',
  }
];
