export const WardMeetingFeilds = [
  {
    id: '1',
    label: 'Meeting Date',
    type: 'default',
    text: 'date',
    name:'meetinG_STARTDATE',
    placeholder: 'Meeting Date',
  },
  {
    id: '2',
    label: 'Meeting Start Time',
    type: 'default',
    text: 'time',
    name:'meetinG_STARTTIME',
    placeholder: 'Meeting Start Time',
  },{
    id: '3',
    label: 'Meeting End Date',
    type: 'default',
    text: 'date',
    name:'meetinG_ENDDATE',
    placeholder: 'Meeting End Date',
  },
  ,{
    id: '4',
    label: 'Meeting End Time',
    type: 'default',
    text: 'time',
    name:'meetinG_ENDTIME',
    placeholder: 'Meeting End Time',
  },
  {
    id: '5',
    label: 'Location',
    type: 'default',
    name:'location',
    // text: 'textarea',
    placeholder: 'Location',
  },
  {
    id: '6',
    label: 'Subject',
    type: 'default',
    name:'subject',
    // text: 'textarea',
    placeholder: 'Subject',
  },
  {
    id: '7',
    label: 'Meeting Details',
    type: 'default',
    text: 'textarea',
    name:'meetinG_DETAILS',
    placeholder: 'Meeting Details',
  },
  // {
  //   id: '3',
  //   label: 'Category',
  //   type: 'default',
  //   text: 'dropdown',
  //   placeholder: 'Category',
  // },
  // {
  //   id: '4',
  //   label: 'Crime Hotspot Details',
  //   type: 'default',
  //   text: 'tetarea',
  //   placeholder: 'Crime Hotspot Details',
  // },
  // {
  //   id: '8',
  //   label: 'Ward Number',
  //   type: 'numeric',
  //   text: 'numeric',
  //   placeholder: 'Ward Number',
  //   name:'WARD_NO',
  // },
  // {
  //   id: '9',
  //   label: 'Expire Date',
  //   type: 'default',
  //   text: 'date',
  //   name:'expirY_DETAILS',
  //   placeholder: 'Expire Data',
  // }
  ];
  